### ISSUE TITLE
Reedireccion al fallar o cancelar un pago

### ISSUE THREAD

**Issue by javialon26** [crevillo/payum-redsys#26]
Cuando un pago es rechazado o se cancela desde el boton de cancelar, redsys no redirecciona nuevamente al sitio sino que redirecciona a la url de capture y esta nuevamente lleva al pago de redsys pero indicando el error numero de pedido repetido. Esto es asi o es un error?

**Comment by crevillo** [comment]
no consigo reproducir eso. en mi caso lleva a una página de fail que tengo definida...

**Comment by javialon26** [comment]
Hola como esas? Gracias por responder tan rapido, es bastante raro el problema, te adjunto como tengo configurado el proyecto, quiza estoy haciendo algo mal.

Estoy usando Symfony 2.8, Doctrine, Payum 2.0 y la ultima version de tu gateway.

**config.yml**
```
payum:
    security:
        token_storage:
            AppBundle\Entity\PaymentToken: { doctrine: orm }
    storages:
        AppBundle\Entity\Payment: { doctrine: orm }
    gateways:
        redsys:
            factory: redsys
            merchant_code: "%payment_merchant_code%"
            terminal: "%payment_terminal%"
            secret_key: "%payment_secret_key%"
            sandbox: "%payment_sandbox%"
```

**services.yml**
```
payment.redsys.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Crevillo\Payum\Redsys\RedsysGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: redsys }
```

Payment y PaymentToken
```
<?php
// src/AppBundle/Entity/PaymentToken.php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Payum\Core\Model\Token;

/**
 * @ORM\Table
 * @ORM\Entity
 */
class PaymentToken extends Token
{
}

<?php
// src/AppBundle/Entity/Payment.php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Payum\Core\Model\Payment as BasePayment;

/**
 * @ORM\Table
 * @ORM\Entity
 */
class Payment extends BasePayment
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     *
     * @var integer $id
     */
    protected $id;

    /**
     * @ORM\OneToOne(targetEntity="Shipping", inversedBy="payment")
     * @ORM\JoinColumn(name="shipping_id", referencedColumnName="id")
     */
    protected $shipping;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set shipping
     *
     * @param \AppBundle\Entity\Shipping $shipping
     *
     * @return Payment
     */
    public function setShipping(\AppBundle\Entity\Shipping $shipping = null)
    {
        $this->shipping = $shipping;

        return $this;
    }

    /**
     * Get shipping
     *
     * @return \AppBundle\Entity\Shipping
     */
    public function getShipping()
    {
        return $this->shipping;
    }
}
```

y en el controller:
```
$payum = $this->get('payum');

$storage = $payum->getStorage('AppBundle\Entity\Payment');

$payment = $storage->create();
$payment->setNumber($this->createOrderNumber($shippment->getId()));
$payment->setCurrencyCode('EUR');
$payment->setTotalAmount($shippment->getPrice()*100);
$payment->setDescription('Pago del envio.');
$payment->setShipping($shippment);
$payment->setClientEmail($shippment->getEmail());

$storage->update($payment);

$captureToken = $payum->getTokenFactory()->createCaptureToken(
    'redsys', 
    $payment, 
    'order_step2'
);

return $this->redirect($captureToken->getTargetUrl());
```

En el parameters.yml tengo todo bien configurado y el parametro sandbox en false. En el controller la ruta order_step2 existe. 

Al parecer todo funciona, el pago se crea en la tabla payment y tambien los tokens en su tabla, pero como comentaba, una vez que estoy en el pago, cuando lo cancelo, redsys me envia a la url de capture y desde aqui vuelvo al form de pago con el error.

Gracias
