### ISSUE TITLE
Fallo al conectar con el TPV

### ISSUE THREAD

**Issue by bnd170** [crevillo/payum-redsys#29]
Codigo de error: SIS0042 La firma enviada no es correcta 

Esto ocurre al enviar al cliente al TPV.

La secret_key y el merchant_code estan correctamente puestos.

Puede deberse a un bug?

**Comment by crevillo** [comment]
no lo creo... nadie ha reportado esto antes y hay basante gente usándolo (creo)...

**Comment by bnd170** [comment]
¿Podrias echarme un cable?

Estoy tratando de usarlo con Sylius y Payum (Que viene integrado) Paypal me funciona sin problemas.

Aqui te dejo la configuracion que tengo:

Este servicio lo he cogido de otro Issue abierto porque no hay configuracion para el factory en YML
```
services:
    payment.redsys.gateway_factory:
            class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
            arguments: [Crevillo\Payum\Redsys\RedsysGatewayFactory]
            tags:
                - { name: payum.gateway_factory_builder, factory: redsys }
```
```
payum:
    gateways:
        redsys:
            factory: redsys
            merchant_code: "CODIGO"
            terminal: "001"
            secret_key: "KEY"
            sandbox: true
```

**Comment by crevillo** [comment]
no lo he llegado a usar con Sylius todavía...

**Comment by bnd170** [comment]
Ignoro si hay diferencia de usarlo con Sylius o no, lo he puesto como curiosidad, no sabia que era un dato relevante.

**Comment by crevillo** [comment]
en principio la configuración que tienes me parece correcta. el error te lo está dando el banco porque dice que la firma no es la correcta. el api forma la firma y eso está testado. 
en la empresa en la que trabajaba antes, esta librería se está usando y ahora mismo está en producción. De ahí que te diga que no me parezca que sea problema de la librería aquí...

Pero si encuentras el error, por favor dímelo. 
Gracias.

**Comment by bnd170** [comment]
No dudo que funciona, solo intento que también lo haga en mi app :)

Podrias decirme donde montas el formulario para enviarselo a redsys? No lo encuentro y me gustaria debugearlo.

**Comment by crevillo** [comment]
eso normalmente lo deberías hacer en tu aplicación. la librería como tal no te da ese formulario...

**Comment by bnd170** [comment]
¿El que se envia directamente a Redsys rellenado con la transacción? 

Estoy viendo que en CaptureAction haces un HttpPostRedirect, intuyo que es ahi donde le envias a Redsys la información del pedido.

**Comment by crevillo** [comment]
sí, pero lo que le paso a ese lo tengo fuera de la librería.

**Comment by bnd170** [comment]
Solo me queda pensar que estoy poniendo mal los datos, hace no mucho integré una pasarela de Redsys por cuenta propia y no me costó tanto.

A ver si me puedes echar un cable, he leido por foros que la clave de encriptacion es de 20 caracteres, pero en la cuenta del cliente, en Ver claves hay dos y ninguna es de 20 caracteres:

![pasare](https://cloud.githubusercontent.com/assets/5690663/20407119/4baa9e5c-ad10-11e6-9772-9e9af0109da7.png)

Cual de las dos es la que va en `secret_key`?

**Comment by bnd170** [comment]
Nada, ya esta solucionado, el cliente tiene el TPV en modo produccion y no me dejaba acceder a el con sandbox.

**Comment by Vegekku** [comment]
Buenas @bnd170 estoy implementando payum/redsys en Sylius 1.2.4. He añadidos las líneas de código tanto a services.yml como config.yml, y no he hecho nada más. Esperaba que con esas modificaciones apareciera la opción de pago en el proceso de compra.
Por lo que veo, no se si debo añadir el FormType correspondiente para crear un payment desde el admin de Sylius, o debo añadir algo más en alguna parte.

**Comment by h3llr4iser** [comment]
Yo lo tengo así, por si te sirve de ayuda:
config.yml
```
sylius_payment:
    gateways:
        redsys: Redsys
```

RedsysGatewayConfigurationType.php
```
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\NotBlank;

class RedsysGatewayConfigurationType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('merchant_code', TextType::class, [
                'label' => 'Merchant Code',
                'constraints' => [
                    new NotBlank([
                        'message' => 'sylius.gateway_config.redsys.merchant_code.not_blank',
                        'groups' => 'sylius',
                    ])
                ],
            ])
            ->add('terminal', TextType::class, [
                'label' => 'Terminal',
                'constraints' => [
                    new NotBlank([
                        'message' => 'sylius.gateway_config.redsys.terminal.not_blank',
                        'groups' => 'sylius',
                    ])
                ],
            ])
            ->add('secret_key', TextType::class, [
                'label' => 'Secret Key',
                'constraints' => [
                    new NotBlank([
                        'message' => 'sylius.gateway_config.redsys.secret_key.not_blank',
                        'groups' => 'sylius',
                    ])
                ],
            ])
            ->add('sandbox', CheckboxType::class, [
                'label' => 'Sandbox'
            ])

        ;
    }
}
```

services.xml
```
<service id="app.form_type_payment.redsys_gateway_configuration" class="AppBundle\Form\Type\Payment\RedsysGatewayConfigurationType">
            <tag name="sylius.gateway_configuration_type" type="redsys" label="app.payum_gateway_factory.redsys" />
            <tag name="form.type" />
        </service>

        <service id="payment.redsys.gateway_factory" class="Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder">
            <tag name="payum.gateway_factory_builder" factory="redsys"/>
            <argument>AppBundle\Payum\Factory\RedsysGatewayFactory</argument>
        </service>
```

**Comment by bnd170** [comment]
Creo recordar que tenias, una vez configurada la pasarela, configurarlo a nivel de panel de administracion para el `channel` que desees. @Vegekku

**Comment by Vegekku** [comment]
Ya he logrado que aparezca, ahora estoy a falta de que el cliente me pase sus datos. Estas son las diferencias con vuestros archivos:

config.yml (Tal como viene en la doc: https://docs.sylius.com/en/1.2/book/orders/payments.html#other-payment-gateways)
```yml
payum:
    gateways:
        redsys:
            factory: redsys
```
services.yml
```yml
services:
    # Form Type Redsys Payment
    app.form_type_payment.redsys_gateway_configuration:
        class: AppBundle\Form\Type\RedsysGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: redsys, label: sylius.payum_gateway_factory.redsys }

    # Configure Redsys Payment Factory
    payment.redsys.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Crevillo\Payum\Redsys\RedsysGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: redsys }
```
En este archivo @h3llr4iser pasaba como argumento de `payment.redsys.gateway_factory` _AppBundle\Payum\Factory\RedsysGatewayFactory_, entiendo será una factoria propia. Yo lo mantuve con el código de @bnd170.

Luego el mismo archvo `RedsysGatewayConfigurationType.php` y algunos archivos de traducciones.

Muchas gracias a todos!

**Comment by Vegekku** [comment]
Hola de nuevo. Después de casi 2 meses, ya tengo los datos del cliente. Los registré desde el panel de admin, pero a la hora de hacer el pago obtengo la siguiente excepción: _The merchant_code, terminal, secret_key fields are required._

He probado la config inicial de @bnd170 añadiéndola al mio:
```yml
payum:
    gateways:
        redsys:
            factory: redsys
            merchant_code: "CODIGO"
            terminal: "001"
            secret_key: "KEY"
            sandbox: true
```
Y entonces si accede al entorno test. Deduzco entonces que payum no está tomando los datos de la base de datos con el formulario creado con el código de @h3llr4iser 

Podéis ayudarme a detectar por qué no obtiene los datos de base de datos?
